### ISSUE TITLE
What Is This

### ISSUE THREAD

**Issue by SharkFinPro** [SharkFinProductions/Shark.js#1]

**Comment by XtremePlayzCODE** [comment]
a library that controls DOM

**Comment by SharkFinPro** [comment]
k
ive been working on diep multiplayer

**Comment by SharkFinPro** [comment]
see my "ermm" repo on c9

**Comment by XtremePlayzCODE** [comment]
ermm

**Comment by XtremePlayzCODE** [comment]
im not dead btw

**Comment by SharkFinPro** [comment]
kk

**Comment by XtremePlayzCODE** [comment]
lol

**Comment by SharkFinPro** [comment]
ugh
need to rewrite collisions 4 diep

**Comment by XtremePlayzCODE** [comment]
yeh

**Comment by XtremePlayzCODE** [comment]
DUDE I NEED HELP

**Comment by SharkFinPro** [comment]
With What?

**Comment by XtremePlayzCODE** [comment]
DISCORD NOWWW

**Comment by XtremePlayzCODE** [comment]
DWAN QE12E8812E1TE7811831T7E2 YE9QhDUCKIES

**Comment by SharkFinPro** [comment]
I Cant...at school

**Comment by SharkFinPro** [comment]
Science :/
Be home in 5 or so hours

**Comment by XtremePlayzCODE** [comment]
FACK

**Comment by SharkFinPro** [comment]
Tell me The Problem Here

**Comment by SharkFinPro** [comment]
Or Gitter

**Comment by XtremePlayzCODE** [comment]
get back 2 learnin boi

**Comment by SharkFinPro** [comment]
lol
playign kahoot

**Comment by XtremePlayzCODE** [comment]
ill fgigure this shit out

**Comment by SharkFinPro** [comment]
dont wanna

**Comment by SharkFinPro** [comment]
tell me the problem :D

**Comment by XtremePlayzCODE** [comment]
kk ill stay here until 5pm
(my time)

**Comment by SharkFinPro** [comment]
ok...
TELL ME THE PROBLEM

**Comment by XtremePlayzCODE** [comment]
i need help making agar.io and diep.io players to use with a custom server, not using node

**Comment by SharkFinPro** [comment]
:|
Why

**Comment by XtremePlayzCODE** [comment]
or processing

**Comment by SharkFinPro** [comment]
ok...

**Comment by XtremePlayzCODE** [comment]
ogarul is dead now

**Comment by SharkFinPro** [comment]
lol no

**Comment by XtremePlayzCODE** [comment]
so ofc im gonna make a new server

**Comment by XtremePlayzCODE** [comment]
and diep server cuz i hate being killed by good people in maze

**Comment by SharkFinPro** [comment]
its not ded
They are just making a betetr version

**Comment by XtremePlayzCODE** [comment]
and to make my own tanks and play with bots :D

**Comment by SharkFinPro** [comment]
The stats is on the forums page

**Comment by XtremePlayzCODE** [comment]
nehemiah is suckish

**Comment by SharkFinPro** [comment]
lol so true

**Comment by XtremePlayzCODE** [comment]
so... i need it

**Comment by SharkFinPro** [comment]
look at meh diep clone...download it

**Comment by SharkFinPro** [comment]
gonna code bai

**Comment by XtremePlayzCODE** [comment]
bai

**Comment by XtremePlayzCODE** [comment]
SHITTTTT

**Comment by XtremePlayzCODE** [comment]
i never copy code tho :(
